---
# Ansible Galaxy collections required for this project
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: community.general
    version: ">=7.0.0"
