- name: show_version
  tags: show_version
  hosts: all
  connection: network_cli
  vars:
    ansible_network_os: eltex.esr.esr
    esr_commands: show version
  collections:
    - eltex.esr
  gather_facts: False
  tasks:
    - name: show version data
      include_tasks: base_tasks/commands_task.yml
