- name: update_firmware
  tags: update_firmware
  connection: network_cli
  hosts: all
  collections: eltex.esr
  vars:
    ansible_network_os: eltex.esr.esr
    ansible_command_timeout: 120
  gather_facts: False
  tasks:
    - name: include copy tasks
      include_tasks: base_tasks/copy_task.yml
    - name: include change to inactive image tasks
      include_tasks: base_tasks/change_to_inactive_image_tasks.yml
    - name: include reload tasks
      include_tasks: base_tasks/reload_tasks.yml